# -*- coding: utf-8 -*-
"""soal-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ugayCig6fppqqaWeHxHzGQiAJHvdocDJ
"""

import math

phi = math.pi

phi

r = int(input('jari-jari: '))

luas_lingkaran_r7 = round(phi*r*r, 2)

luas_lingkaran_r7

r = int(input('jari-jari: '))

luas_lingkaran_r10 = round(phi*r*r, 2)

luas_lingkaran_r10

